#include "token.h"
#include <stdio.h>

const char *tokenTypeToString(TokenType type) {
  switch (type) {
  case TOKEN_LEFT_PAREN:
    return "TOKEN_LEFT_PAREN";
  case TOKEN_RIGHT_PAREN:
    return "TOKEN_RIGHT_PAREN";
  case TOKEN_LEFT_BRACE:
    return "TOKEN_LEFT_BRACE";
  case TOKEN_RIGHT_BRACE:
    return "TOKEN_RIGHT_BRACE";
  case TOKEN_LEFT_BRACKET:
    return "TOKEN_LEFT_BRACKET";
  case TOKEN_RIGHT_BRACKET:
    return "TOKEN_RIGHT_BRACKET";
  case TOKEN_COMMA:
    return "TOKEN_COMMA";
  case TOKEN_COLON:
    return "TOKEN_COLON";
  case TOKEN_DOT:
    return "TOKEN_DOT";
  case TOKEN_MINUS:
    return "TOKEN_MINUS";
  case TOKEN_PLUS:
    return "TOKEN_PLUS";
  case TOKEN_SEMICOLON:
    return "TOKEN_SEMICOLON";
  case TOKEN_SLASH:
    return "TOKEN_SLASH";
  case TOKEN_STAR:
    return "TOKEN_STAR";
  case TOKEN_BANG:
    return "TOKEN_BANG";
  case TOKEN_BANG_EQUAL:
    return "TOKEN_BANG_EQUAL";
  case TOKEN_EQUAL:
    return "TOKEN_EQUAL";
  case TOKEN_EQUAL_EQUAL:
    return "TOKEN_EQUAL_EQUAL";
  case TOKEN_FAT_ARROW:
    return "TOKEN_FAT_ARROW";
  case TOKEN_GREATER:
    return "TOKEN_GREATER";
  case TOKEN_GREATER_EQUAL:
    return "TOKEN_GREATER_EQUAL";
  case TOKEN_LESS:
    return "TOKEN_LESS";
  case TOKEN_LESS_EQUAL:
    return "TOKEN_LESS_EQUAL";
  case TOKEN_IDENTIFIER:
    return "TOKEN_IDENTIFIER";
  case TOKEN_STRING:
    return "TOKEN_STRING";
  case TOKEN_NUMBER:
    return "TOKEN_NUMBER";
  case TOKEN_AND:
    return "TOKEN_AND";
  case TOKEN_STRUCT:
    return "TOKEN_STRUCT";
  case TOKEN_IMPL:
    return "TOKEN_IMPL";
  case TOKEN_TRAIT:
    return "TOKEN_TRAIT";
  case TOKEN_ELSE:
    return "TOKEN_ELSE";
  case TOKEN_FALSE:
    return "TOKEN_FALSE";
  case TOKEN_FOR:
    return "TOKEN_FOR";
  case TOKEN_FUN:
    return "TOKEN_FUN";
  case TOKEN_IF:
    return "TOKEN_IF";
  case TOKEN_NIL:
    return "TOKEN_NIL";
  case TOKEN_OR:
    return "TOKEN_OR";
  case TOKEN_PRINT:
    return "TOKEN_PRINT";
  case TOKEN_PUB:
    return "TOKEN_PUB";
  case TOKEN_RETURN:
    return "TOKEN_RETURN";
  case TOKEN_SELF:
    return "TOKEN_SELF";
  case TOKEN_TRUE:
    return "TOKEN_TRUE";
  case TOKEN_TYPE:
    return "TOKEN_TYPE";
  case TOKEN_VAR:
    return "TOKEN_VAR";
  case TOKEN_LET:
    return "TOKEN_LET";
  case TOKEN_WHILE:
    return "TOKEN_WHILE";
  case TOKEN_MODULO:
    return "TOKEN_MODULO";
  case TOKEN_BREAK:
    return "TOKEN_BREAK";
  case TOKEN_CONTINUE:
    return "TOKEN_CONTINUE";
  case TOKEN_ERROR:
    return "TOKEN_ERROR";
  case TOKEN_EOF:
    return "TOKEN_EOF";
  default:
    fprintf(stderr, "Unknown token: %d", type);
    return "UNKNOWN TOKEN";
  }
}
