name: Verify

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Deps
        run: sudo apt-get update && sudo apt-get install -y libreadline8 libreadline-dev lcov

      - name: Generate Version C File
        run: ./scripts/generate_version_c.sh ./build/generated/version.c VERSION.txt

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Test (With Coverage)
        run: ./scripts/coverage.sh

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: krb
          path: ./build/krb
          if-no-files-found: error
          overwrite: true

      - name: Upload coverage file
        uses: actions/upload-artifact@v4
        with:
          name: lcov.info
          path: ./lcov.info
          if-no-files-found: error
          overwrite: true

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: lcov.html
          path: ./build/coverage_html
          if-no-files-found: error
          overwrite: true
